before_install:
  - sudo apt-get install default-jre
  - perl -Mthreads -e 'print "this perl is multithreaded\n";'
  - sudo apt-get install ncbi-blast+
  - export PATH=$PATH:$(pwd)/scripts
  - export PERL5LIB=PERL5LIB:$HOME/lib/perl5
    # Say no for all bioperl prompts
  # two more modules
  - cpanm -l ~ File::Slurp
  - cpanm -l ~ String::Escape
install:
  - make install
script: 
  - bash scripts/testInstallation.sh
  - bash scripts/testScripts.sh
language: shell
addons:
  apt:
    packages:
      -bioperl
