before_install:
  # workaround for silly public keys bug in travis
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157; 
  #- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - perl -Mthreads -e 'print "this perl is multithreaded\n";'
  - export PATH=$PATH:$(pwd)/scripts
  - export PERL5LIB=PERL5LIB:$HOME/lib/perl5
  # Ensure two bioperl modules
  - cpanm -l ~ File::Slurp
  - cpanm -l ~ String::Escape
install:
  - make install
script: 
  - bash scripts/testInstallation.sh
  - bash scripts/testScripts.sh
language: shell
addons:
  apt:
    packages:
      -bioperl
      -default-jre
      -ncbi-blast+
